/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projetos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Projetos */
        get: operations["listar_projetos_projetos_get"];
        put?: never;
        /** Criar Projeto */
        post: operations["criar_projeto_projetos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hipoteses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Hipoteses */
        get: operations["listar_hipoteses_hipoteses_get"];
        put?: never;
        /** Criar Hipotese */
        post: operations["criar_hipotese_hipoteses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HipoteseCreate */
        HipoteseCreate: {
            /**
             * Projeto Id
             * @example 1
             */
            projeto_id: number;
            /**
             * Enunciado
             * @example Se o copiloto sugerir enquadramentos a partir do histórico de MVPs, então o enquadramento inicial cai de 8h para 2h
             */
            enunciado: string;
            /**
             * Metrica
             * @example Tempo até enquadramento concluído
             */
            metrica: string;
            /**
             * Criterio Aceite
             * @example 4 de 5 produtos em <= 2h
             */
            criterio_aceite: string;
        };
        /** HipoteseOut */
        HipoteseOut: {
            /** Id */
            id: number;
            /** Projeto Id */
            projeto_id: number;
            /** Enunciado */
            enunciado: string;
            /** Metrica */
            metrica: string;
            /** Criterio Aceite */
            criterio_aceite: string;
            /** Status */
            status: string;
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
        };
        /** ProjetoCreate */
        ProjetoCreate: {
            /**
             * Nome
             * @example Paris Group Copilot
             */
            nome: string;
            /**
             * Contexto
             * @example PM de venture studio iniciando um novo MVP
             */
            contexto: string;
            /**
             * Dor Usuario
             * @example Marina gasta ~8h por produto novo remontando enquadramento do zero
             */
            dor_usuario: string;
        };
        /** ProjetoOut */
        ProjetoOut: {
            /** Id */
            id: number;
            /** Nome */
            nome: string;
            /** Contexto */
            contexto: string;
            /** Dor Usuario */
            dor_usuario: string;
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    listar_projetos_projetos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjetoOut"][];
                };
            };
        };
    };
    criar_projeto_projetos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjetoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjetoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_hipoteses_hipoteses_get: {
        parameters: {
            query?: {
                projeto_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HipoteseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_hipotese_hipoteses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HipoteseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HipoteseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
